In [2]:
import torch
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
print(torch.__version__)


2.3.0+cpu


In [3]:
scalar = torch.Tensor([7,7])
scalar

tensor([7., 7.])

In [4]:
scalar.shape

torch.Size([2])

In [5]:
random_tensor = torch.rand(size=(3,4))
random_tensor, random_tensor.dtype

(tensor([[0.2764, 0.2924, 0.0808, 0.7887],
         [0.2917, 0.6738, 0.3133, 0.6277],
         [0.1338, 0.0951, 0.7915, 0.6824]]),
 torch.float32)

In [6]:
zeros = torch.zeros(size=(3,3))
zeros, zeros.dtype, zeros.ndim, zeros.shape

(tensor([[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]),
 torch.float32,
 2,
 torch.Size([3, 3]))

In [7]:
torch.ones(size=(2,3))

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [8]:
arr = torch.arange(1,10,2)

In [9]:
torch.zeros_like(input = arr)

tensor([0, 0, 0, 0, 0])

In [10]:
float_32_tensor  = torch.tensor(
    [1.0, 2.0, 3.0, 4.0 ],
    dtype = None,
    device  =None,
    requires_grad=False
)

In [31]:
x = float_32_tensor
x = x.unsqueeze(-1)
orders_f = 4
orders_t = 3
ordering_f = torch.arange(1,orders_f)
ordering_t = torch.arange(1,orders_t)
x = torch.cat([torch.sin(ordering_f*x), torch.cos(ordering_t*x),torch.pow(ordering, x),x], dim=-1)
x

tensor([[ 0.8415,  0.9093,  0.1411,  0.5403, -0.4161,  1.0000,  2.0000,  3.0000,
          1.0000],
        [ 0.9093, -0.7568, -0.2794, -0.4161, -0.6536,  1.0000,  4.0000,  9.0000,
          2.0000],
        [ 0.1411, -0.2794,  0.4121, -0.9900,  0.9602,  1.0000,  8.0000, 27.0000,
          3.0000],
        [-0.7568,  0.9894, -0.5366, -0.6536, -0.1455,  1.0000, 16.0000, 81.0000,
          4.0000]])